import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from './components/Header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="p-2">
          <main>{children}</main>  
        </div>
      </body>
    </html>
  );
}
